# Generated by Django 4.2.3 on 2023-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
