# Generated by Django 4.2.3 on 2023-08-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_fix',
            fields=[
                ('uid', models.CharField(primary_key=True, serialize=False)),
                ('owner_id', models.CharField()),
                ('media_id', models.CharField()),
                ('caption', models.CharField()),
                ('media_url', models.CharField()),
                ('permalink', models.CharField()),
                ('timestamp', models.CharField()),
            ],
            options={
                'db_table': 'media_fix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media_info',
            fields=[
                ('uid', models.CharField(primary_key=True, serialize=False)),
                ('media_id', models.CharField()),
                ('date', models.CharField()),
                ('like_count', models.CharField()),
                ('comments_count', models.CharField()),
            ],
            options={
                'db_table': 'media_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users_fix',
            fields=[
                ('ig_id', models.CharField(primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('username', models.CharField()),
                ('website', models.CharField()),
                ('biography', models.CharField()),
            ],
            options={
                'db_table': 'users_fix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('uid', models.CharField(primary_key=True, serialize=False)),
                ('ig_id', models.CharField()),
                ('date', models.CharField()),
                ('follows_count', models.CharField()),
                ('followers_count', models.CharField()),
                ('media_count', models.CharField()),
            ],
            options={
                'db_table': 'users_info',
                'managed': False,
            },
        ),
    ]
