# Generated by Django 4.2.3 on 2023-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media4', '0002_media_fix_media_info_users_fix_users_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('media_id', models.CharField(primary_key=True, serialize=False)),
                ('tags', models.CharField()),
                ('owner_id', models.CharField()),
            ],
            options={
                'db_table': 'hashtags',
                'managed': False,
            },
        ),
    ]
