# Generated by Django 4.2.3 on 2023-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media_fix',
            fields=[
                ('owner_id', models.BigIntegerField()),
                ('media_fix_id', models.TextField(primary_key=True, serialize=False)),
                ('caption', models.TextField(null=True)),
                ('media_url', models.URLField()),
                ('permalink', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Media_fix',
            },
        ),
        migrations.CreateModel(
            name='Media_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_info_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('like_count', models.IntegerField(null=True)),
                ('comments_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Media_info',
            },
        ),
        migrations.CreateModel(
            name='Users_fix',
            fields=[
                ('users_fix_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('username', models.CharField()),
                ('website', models.URLField(null=True)),
                ('biography', models.TextField()),
            ],
            options={
                'db_table': 'Users_fix',
            },
        ),
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_info_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
            ],
            options={
                'db_table': 'Users_info',
            },
        ),
    ]
