# Generated by Django 4.2.3 on 2023-08-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_fix',
            fields=[
                ('ig_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('username', models.CharField()),
                ('website', models.URLField(null=True)),
                ('biography', models.TextField()),
            ],
            options={
                'db_table': 'User_fix',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id_info', models.BigIntegerField()),
                ('date', models.DateField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
    ]
