# Generated by Django 4.2.3 on 2023-08-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media_date',
            new_name='Media_info',
        ),
        migrations.RenameModel(
            old_name='Users_date',
            new_name='Users_info',
        ),
    ]
