# Generated by Django 4.2.3 on 2023-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('caption', models.TextField()),
                ('media_url', models.URLField()),
                ('permalink', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'media_fix',
            },
        ),
        migrations.CreateModel(
            name='Media_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('date', models.DateField()),
                ('like_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
            ],
            options={
                'db_table': 'media_info',
            },
        ),
        migrations.CreateModel(
            name='Users_fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.IntegerField()),
                ('user_id', models.CharField()),
                ('username', models.CharField()),
                ('website', models.URLField()),
                ('biography', models.TextField()),
            ],
            options={
                'db_table': 'users_fix',
            },
        ),
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.IntegerField()),
                ('date', models.DateField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
            ],
            options={
                'db_table': 'users_info',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
