# Generated by Django 4.2.3 on 2023-08-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='media_fix',
            table='Media_fix',
        ),
        migrations.AlterModelTable(
            name='media_info',
            table='Media_info',
        ),
        migrations.AlterModelTable(
            name='users_fix',
            table='Users_fix',
        ),
        migrations.AlterModelTable(
            name='users_info',
            table='Users_info',
        ),
    ]
