# Generated by Django 4.2.3 on 2023-08-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0002_remove_users_fix_biography_remove_users_fix_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media_fix',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='media_info',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users_fix',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users_info',
            options={'managed': False},
        ),
    ]
