# Generated by Django 4.2.3 on 2023-08-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InfluencerList', '0003_remove_media_info_media_id_remove_users_info_ig_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_fix',
            fields=[
                ('media_id', models.TextField(primary_key=True, serialize=False)),
                ('caption', models.TextField(null=True)),
                ('media_url', models.URLField()),
                ('permalink', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Media_fix',
            },
        ),
        migrations.CreateModel(
            name='Users_fix',
            fields=[
                ('ig_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('username', models.CharField()),
                ('website', models.URLField(null=True)),
                ('biography', models.TextField()),
            ],
            options={
                'db_table': 'Users_fix',
            },
        ),
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
                ('ig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix')),
            ],
            options={
                'db_table': 'Users_info',
            },
        ),
        migrations.CreateModel(
            name='Media_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('like_count', models.IntegerField(null=True)),
                ('comments_count', models.IntegerField(null=True)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.media_fix')),
            ],
            options={
                'db_table': 'Media_info',
            },
        ),
        migrations.AddField(
            model_name='media_fix',
            name='ig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix'),
        ),
    ]
