# Generated by Django 4.2.3 on 2023-08-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0003_alter_media_fix_options_alter_media_info_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='media_fix',
            table='media_fix',
        ),
        migrations.AlterModelTable(
            name='media_info',
            table='media_info',
        ),
        migrations.AlterModelTable(
            name='users_info',
            table='users_info',
        ),
    ]
