# Generated by Django 4.2.3 on 2023-08-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InfluencerList', '0004_remove_media_info_media_id_remove_users_info_ig_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_fix',
            fields=[
                ('media_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('caption', models.TextField()),
                ('media_url', models.TextField()),
                ('permalink', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Media_fix',
            },
        ),
        migrations.CreateModel(
            name='Users_fix',
            fields=[
                ('ig_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField()),
                ('username', models.CharField()),
                ('website', models.TextField()),
                ('biography', models.TextField()),
            ],
            options={
                'db_table': 'Users_fix',
            },
        ),
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('follows_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
                ('ig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix')),
            ],
            options={
                'db_table': 'Users_info',
            },
        ),
        migrations.CreateModel(
            name='Media_info',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('like_count', models.IntegerField(null=True)),
                ('comments_count', models.IntegerField(null=True)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.media_fix')),
            ],
            options={
                'db_table': 'Media_info',
            },
        ),
        migrations.AddField(
            model_name='media_fix',
            name='ig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix'),
        ),
    ]
