# Generated by Django 4.2.3 on 2023-08-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0004_alter_media_fix_table_alter_media_info_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media_fix',
        ),
        migrations.DeleteModel(
            name='Media_info',
        ),
        migrations.DeleteModel(
            name='Users_fix',
        ),
        migrations.DeleteModel(
            name='Users_info',
        ),
    ]
