# Generated by Django 4.2.3 on 2023-08-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_info',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='users_info',
            name='ig_id',
        ),
        migrations.DeleteModel(
            name='Media_fix',
        ),
        migrations.DeleteModel(
            name='Media_info',
        ),
        migrations.DeleteModel(
            name='Users_info',
        ),
    ]
