# Generated by Django 4.2.3 on 2023-08-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_fix',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
