# Generated by Django 4.2.3 on 2023-08-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0006_alter_users_fix_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_info',
            name='media_id',
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='ig_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='media_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='ig_id',
            field=models.BigIntegerField(),
        ),
    ]
