# Generated by Django 4.2.3 on 2023-08-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0006_media_fix_users_info_media_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media_fix',
            new_name='Media_f',
        ),
        migrations.RenameModel(
            old_name='Media_info',
            new_name='Media_i',
        ),
        migrations.RenameModel(
            old_name='Users_fix',
            new_name='Users_f',
        ),
        migrations.RenameModel(
            old_name='Users_info',
            new_name='Users_i',
        ),
        migrations.AlterModelTable(
            name='media_f',
            table='Media_f',
        ),
        migrations.AlterModelTable(
            name='media_i',
            table='Media_i',
        ),
        migrations.AlterModelTable(
            name='users_f',
            table='Users_f',
        ),
        migrations.AlterModelTable(
            name='users_i',
            table='Users_i',
        ),
    ]
