# Generated by Django 4.2.3 on 2023-08-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0007_remove_media_info_media_id_alter_media_fix_ig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_info',
            name='media_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.media_fix'),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='ig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix'),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='media_id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='media_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='permalink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='users_fix',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='ig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix'),
        ),
    ]
