# Generated by Django 4.2.3 on 2023-08-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0007_rename_media_fix_media_f_rename_media_info_media_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_i',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='users_i',
            name='ig_id',
        ),
        migrations.DeleteModel(
            name='Media_f',
        ),
        migrations.DeleteModel(
            name='Media_i',
        ),
        migrations.DeleteModel(
            name='Users_f',
        ),
        migrations.DeleteModel(
            name='Users_i',
        ),
    ]
