# Generated by Django 4.2.3 on 2023-08-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0008_media_info_media_id_alter_media_fix_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_fix',
            name='ig_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='media_info',
            name='media_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='ig_id',
            field=models.BigIntegerField(),
        ),
    ]
