# Generated by Django 4.2.3 on 2023-08-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0009_alter_media_fix_ig_id_alter_media_info_media_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_info',
            name='key',
        ),
        migrations.RemoveField(
            model_name='users_info',
            name='key',
        ),
        migrations.AddField(
            model_name='media_info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='ig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix'),
        ),
        migrations.AlterField(
            model_name='media_fix',
            name='media_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media_info',
            name='media_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.media_fix'),
        ),
        migrations.AlterField(
            model_name='users_fix',
            name='ig_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='ig_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerList.users_fix'),
        ),
    ]
