# Generated by Django 4.2.3 on 2023-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerList', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
