wordcloud={
'2__yun__2' : [
    {'text':"언니", 'weight': 182},
    {'text':"디엠", 'weight':43},
    {'text':"다윤님", 'weight':38},
    {'text':"정보", 'weight':31},
    {'text':"예뻐요", 'weight':29},
    {'text':"존예", 'weight':26},
    {'text':"구매", 'weight':24},
    {'text':"공구", 'weight':22},
    {'text':"부탁드립니다", 'weight':21},
    {'text':"미모", 'weight':16},
    {'text':"공주", 'weight':16}
],

'a_arang_' : [
 {'text':"아랑", 'weight':166},
 {'text':"구매", 'weight':61},
 {'text':"낫츠", 'weight':38},
 {'text':"피부", 'weight':34},
 {'text':"정보", 'weight':30},
 {'text':"제품", 'weight':30},
 {'text':"컬러", 'weight':29},
 {'text':"존예", 'weight':27},
 {'text':"메이크업", 'weight':23},
 {'text':"색상", 'weight':23},
 {'text':"궁금해요", 'weight':19},
 {'text':"추천", 'weight':19},
 {'text':"핑크", 'weight':19},
 {'text':"예뻐요", 'weight':17}],

'areunmsongee ' : [
{'text':"언니", 'weight':104},
 {'text':"구매", 'weight':60},
 {'text':"인증", 'weight':57},
 {'text':"완료", 'weight':43},
 {'text':"너무", 'weight':20},
 {'text':"스껄", 'weight':18},
 {'text':"정보", 'weight':16},
 {'text':"리프", 'weight':16},
 {'text':"크림", 'weight':15},
 {'text':"토너", 'weight':14},
 {'text':"어성초", 'weight':13}],

'calarygirl_a' : [
{'text':"회사원", 'weight':83},
 {'text':"사진", 'weight':32},
 {'text':"찰떡", 'weight':25},
 {'text':"예뻐요", 'weight':24},
 {'text':"영상", 'weight':22},
 {'text':"원피스", 'weight':19},
 {'text':"공주", 'weight':19},
 {'text':"미모", 'weight':16},
 {'text':"떠히", 'weight':14},
 {'text':"머리", 'weight':13},
 {'text':"요즘", 'weight':13}],

'doublesoup' : [
{'text':"습습", 'weight':52},
 {'text':"예뻐요", 'weight':24},
 {'text':"사진", 'weight':23},
 {'text':"영상", 'weight':19},
 {'text':"찰떡", 'weight':13},
 {'text':"천사", 'weight':12},
 {'text':"YouTube", 'weight':10},
 {'text':"공주", 'weight':10},
 {'text':"존예", 'weight':10}],

'fallininm' : [
{'text':"정보", 'weight':60},
 {'text':"예뻐요", 'weight':45},
 {'text':"사랑", 'weight':41},
 {'text':"사진", 'weight':39},
 {'text':"공주", 'weight':38},
 {'text':"이뻐요", 'weight':30},
 {'text':"영상", 'weight':29},
 {'text':"미모", 'weight':25},
 {'text':"틴트", 'weight':24},
 {'text':"얼굴", 'weight':23},
 {'text':"렌즈", 'weight':21},
 {'text':"이뻐", 'weight':21}],

'hamnihouse' : [
{'text':"사이판", 'weight':39},
 {'text':"피부", 'weight':37},
 {'text':"골프", 'weight':31},
 {'text':"햄니", 'weight':30},
 {'text':"모델", 'weight':26},
 {'text':"컬러", 'weight':19},
 {'text':"사진", 'weight':18},
 {'text':"화보", 'weight':18},
 {'text':"최고", 'weight':16},
 {'text':"여신", 'weight':13},
 {'text':"여름", 'weight':13}],

'hyojinc_' : [
{'text':"효진", 'weight':142},
 {'text':"정보", 'weight':34},
 {'text':"사랑", 'weight':27},
 {'text':"사진", 'weight':23},
 {'text':"얼굴", 'weight':21},
 {'text':"컬러", 'weight':20},
 {'text':"메이크업", 'weight':20},
 {'text':"뉴욕", 'weight':20},
 {'text':"찰떡", 'weight':18},
 {'text':"조효진", 'weight':17},
 {'text':"존예", 'weight':16},
 {'text':"구매", 'weight':16},
 {'text':"쉐딩", 'weight':16},
 {'text':"예뻐요", 'weight':15},
 {'text':"영상", 'weight':15},
 {'text':"제품", 'weight':15},
 {'text':"최고", 'weight':14}],

'im_jella_' : [
{'text':"젤라", 'weight':63},
 {'text':"피부", 'weight':40},
 {'text':"구매", 'weight':23},
 {'text':"패드", 'weight':20},
 {'text':"쿠션", 'weight':15},
 {'text':"사진", 'weight':14},
 {'text':"얼굴", 'weight':14},
 {'text':"최고", 'weight':12},
 {'text':"정보", 'weight':12},
 {'text':"각질", 'weight':12},
 {'text':"사랑", 'weight':11},
{'text':"인어공주", 'weight':11}],

'kisy0729' : [
{'text':"영기", 'weight':67},
 {'text':"구매", 'weight':56},
 {'text':"완료", 'weight':52},
 {'text':"정보", 'weight':36},
 {'text':"어디", 'weight':31},
 {'text':"사진", 'weight':27},
 {'text':"강아지", 'weight':25},
 {'text':"제트", 'weight':21},
 {'text':"토너", 'weight':21},
 {'text':"공구", 'weight':16},
 {'text':"트리", 'weight':16},
 {'text':"궁금해요", 'weight':15},
 {'text':"품절", 'weight':14},
 {'text':"선착순", 'weight':14},
 {'text':"뷰티", 'weight':14}],

'lamuqe_magicup' : [
 {'text':"정보", 'weight':29},
 {'text':"좋은", 'weight':26},
 {'text':"틴트", 'weight':25},
 {'text':"이뻐요", 'weight':24},
 {'text':"예뻐요", 'weight':22},
 {'text':"컬러", 'weight':22},
 {'text':"제품", 'weight':21},
 {'text':"라뮤끄님", 'weight':21},
 {'text':"보배", 'weight':21},
 {'text':"예쁜", 'weight':17},
 {'text':"뷰러", 'weight':15},
 {'text':"정말", 'weight':15},
 {'text':"뮤끄님", 'weight':14},
 {'text':"찰떡", 'weight':13},
 {'text':"어디", 'weight':12},
 {'text':"궁금해요", 'weight':12},
 {'text':"분위기", 'weight':12},
 {'text':"추천", 'weight':12}],

'leojmakeup' : [
{'text':"레오제이", 'weight':188},
 {'text':"오빠", 'weight':60},
 {'text':"선크림", 'weight':49},
 {'text':"영상", 'weight':39},
 {'text':"쿠션", 'weight':39},
 {'text':"제품", 'weight':38},
 {'text':"피부", 'weight':37},
 {'text':"브러쉬", 'weight':36},
 {'text':"쉐딩", 'weight':34},
 {'text':"믿고", 'weight':26},
 {'text':"추천", 'weight':26},
 {'text':"오레오", 'weight':26},
 {'text':"화장", 'weight':21},
 {'text':"마켓", 'weight':19}],

'makeup_maker_' : [
{'text':"짱아", 'weight':33},
 {'text':"원장", 'weight':28},
 {'text':"구매", 'weight':25},
 {'text':"정보", 'weight':25},
 {'text':"브러쉬", 'weight':20},
 {'text':"눈썹", 'weight':20},
 {'text':"제품", 'weight':18},
 {'text':"메이크업", 'weight':14},
 {'text':"있을까요", 'weight':10},
 {'text':"궁금해요", 'weight':10},
 {'text':"최고", 'weight':8},
 {'text':"공구", 'weight':8}],

'ponysmakeup' : [
{'text':"포니", 'weight':68},
 {'text':"Pony", 'weight':42},
 {'text':"사랑", 'weight':27},
 {'text':"메이크업", 'weight':26},
 {'text':"beautiful", 'weight':19},
 {'text':"pretty", 'weight':15},
 {'text':"love", 'weight':14},
 {'text':"cute", 'weight':14},
 {'text':"영상", 'weight':14},
 {'text':"인형", 'weight':10},
 {'text':"look", 'weight':10},
 {'text':"hair", 'weight':9},
 {'text':"요정", 'weight':9}],

'r_yuhyeju' : [
{'text':"유준", 'weight':117},
 {'text':"혜주", 'weight':102},
 {'text':"엄마", 'weight':92},
 {'text':"애기", 'weight':61},
 {'text':"아기", 'weight':45},
 {'text':"유주", 'weight':41},
 {'text':"가방", 'weight':31},
 {'text':"정보", 'weight':29},
 {'text':"육아", 'weight':22},
 {'text':"영상", 'weight':21},
 {'text':"사랑", 'weight':19}],

'risabae_art' : [
{'text':"사배", 'weight':91},
 {'text':"메이크업", 'weight':57},
 {'text':"예뻐요", 'weight':39},
 {'text':"이사배", 'weight':26},
 {'text':"정보", 'weight':24},
 {'text':"블랙", 'weight':21},
 {'text':"제품", 'weight':18},
 {'text':"공주", 'weight':16},
 {'text':"뷰티", 'weight':15},
 {'text':"찰떡", 'weight':15},
 {'text':"이뻐요", 'weight':14},
 {'text':"메컵", 'weight':13},
 {'text':"팔로우", 'weight':13},
 {'text':"궁금해요", 'weight':12},
 {'text':"좋아요", 'weight':12},
 {'text':"어디", 'weight':12}],

'ssinnim' : [
{'text':"씬님", 'weight':55},
 {'text':"와인", 'weight':13},
 {'text':"우와", 'weight':12},
 {'text':"사진", 'weight':11},
 {'text':"추천", 'weight':10},
 {'text':"이뻐요", 'weight':9},
 {'text':"예뻐요", 'weight':9},
 {'text':"영상", 'weight':9},
 {'text':"이렇게", 'weight':9},
 {'text':"운동", 'weight':8},
 {'text':"좋아요", 'weight':8}],

'vivamoon' : [
{'text':"단발", 'weight':40},
 {'text':"정보", 'weight':34},
 {'text':"여신", 'weight':26},
 {'text':"머리", 'weight':19},
 {'text':"미모", 'weight':18},
 {'text':"이뻐요", 'weight':16},
 {'text':"Love", 'weight':15},
 {'text':"아름다운", 'weight':15},
 {'text':"몸매", 'weight':15},
 {'text':"beautiful", 'weight':11},
 {'text':"비키니", 'weight':11},
 {'text':"Lovely", 'weight':9},
 {'text':"앰플", 'weight':9},
 {'text':"분위기", 'weight':8},
 {'text':"여름", 'weight':8},
 {'text':"이쁨", 'weight':8},
 {'text':"찰떡", 'weight':8},
 {'text':"pretty", 'weight':7},
 {'text':"어울려요", 'weight':7},
 {'text':"매력", 'weight':7},
 {'text':"귀여워요", 'weight':7}],

'yeondukong' : [
 {'text':"사랑", 'weight':24},
 {'text':"사진", 'weight':23},
 {'text':"예뻐요", 'weight':19},
 {'text':"귀여워요", 'weight':16},
 {'text':"귀여워", 'weight':11},
 {'text':"꼬망", 'weight':11},
 {'text':"상큼", 'weight':10},
 {'text':"행복한", 'weight':10},
 {'text':"이뻐요", 'weight':9},
 {'text':"공주", 'weight':8},
 {'text':"찰떡", 'weight':8},
 {'text':"귀여운", 'weight':8}],

'yu__hyewon' : [
{'text':"예뻐", 'weight':33},
 {'text':"혜원", 'weight':29},
 {'text':"정보", 'weight':26},
 {'text':"단발", 'weight':26},
 {'text':"사진", 'weight':19},
 {'text':"얼굴", 'weight':15},
 {'text':"Beautiful", 'weight':14},
 {'text':"구매", 'weight':14},
 {'text':"인형", 'weight':14},
 {'text':"예뻐요", 'weight':13},
 {'text':"예쁜", 'weight':13},
 {'text':"존예", 'weight':12},
 {'text':"예쁘다", 'weight':11},
 {'text':"공주", 'weight':11},
 {'text':"beautiful", 'weight':10},
 {'text':"love", 'weight':9},
 {'text':"이쁜", 'weight':8},
 {'text':"이뻐", 'weight':8},
 {'text':"사랑", 'weight':8},
 {'text':"여신", 'weight':8}],

'yujin_so' : [
{'text':"유진", 'weight':57},
 {'text':"아이", 'weight':41},
 {'text':"소유진", 'weight':34},
 {'text':"좋은", 'weight':31},
 {'text':"엄마", 'weight':31},
 {'text':"이뻐요", 'weight':22},
 {'text':"좋아요", 'weight':22},
 {'text':"예뻐요", 'weight':18},
 {'text':"예쁘다", 'weight':17},
 {'text':"구매", 'weight':17},
 {'text':"제품", 'weight':15}],

'yulri_0i' :[
{'text':"율리", 'weight':245},
 {'text':"율무", 'weight':88},
 {'text':"구매", 'weight':51},
 {'text':"영상", 'weight':43},
 {'text':"박스", 'weight':41},
 {'text':"스위스", 'weight':39},
 {'text':"마켓", 'weight':38},
 {'text':"정보", 'weight':38},
 {'text':"피부", 'weight':33},
 {'text':"얼굴", 'weight':32},
 {'text':"품절", 'weight':31},
 {'text':"데이트", 'weight':30},
 {'text':"피지", 'weight':27},
 {'text':"공주", 'weight':27}
]}

def wordreturn(name):
    return wordcloud[name]

print(wordreturn('hamnihouse'))