# Generated by Django 4.2.3 on 2023-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ig_id', models.CharField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('infocomment', models.IntegerField()),
                ('totalcomment', models.IntegerField()),
                ('inforate', models.FloatField()),
                ('imagecomment', models.IntegerField()),
                ('imagerate', models.FloatField()),
                ('domain', models.IntegerField()),
                ('cute', models.IntegerField()),
                ('pure', models.IntegerField()),
                ('gorg', models.IntegerField()),
                ('maximage', models.CharField()),
                ('maximagerate', models.FloatField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
    ]
